// Sample property data for testing when Typesense is unavailable
export const sampleProperties = [
  {
    id: "sample-property-1",
    title: "Luxury Villa in Lisbon",
    description: "Beautiful 4-bedroom villa with a garden and pool",
    price: 850000,
    price_currency: "EUR",
    bedrooms: 4,
    bathrooms: 3,
    area: 280,
    area_unit: "m²",
    address: "Avenida da Liberdade, Lisbon",
    image_url: "https://placehold.co/600x400/png?text=Luxury+Villa",
    property_type: "Villa",
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-property-2",
    title: "Modern Apartment in Porto",
    description: "Centrally located 2-bedroom apartment with river views",
    price: 320000,
    price_currency: "EUR",
    bedrooms: 2,
    bathrooms: 1,
    area: 95,
    area_unit: "m²",
    address: "Rua das Flores, Porto",
    _geoloc: "41.1456, -8.6126",
    image_url: "https://placehold.co/600x400/png?text=Modern+Apartment",
    property_type: "Apartment",
    created_at: new Date().toISOString(),
  },
  {
    id: "sample-property-3",
    title: "Seaside Cottage in Algarve",
    description: "Charming 3-bedroom cottage with direct beach access",
    price: 450000,
    price_currency: "EUR",
    bedrooms: 3,
    bathrooms: 2,
    area: 120,
    area_unit: "m²",
    address: "Praia da Rocha, Portimão",
    _geoloc: "37.1175, -8.5380",
    image_url: "https://placehold.co/600x400/png?text=Seaside+Cottage",
    property_type: "House",
    created_at: new Date().toISOString(),
  },
];
